CREATE TABLE IF NOT EXISTS user_t (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login varchar(200) NOT NULL,
	main_email varchar(320),
	is_del bool DEFAULT false NOT NULL,
	extra jsonb
);
COMMENT ON COLUMN user_t.id IS 'Идентификатор';
COMMENT ON COLUMN user_t.login IS 'Логин';
COMMENT ON COLUMN user_t.main_email IS 'Основная почта';
COMMENT ON COLUMN user_t.is_del IS 'Удален';
COMMENT ON COLUMN user_t.extra IS 'Дополнительно';

CREATE TABLE IF NOT EXISTS product (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code uuid NOT NULL,
	name varchar(200) NOT NULL
);
COMMENT ON COLUMN product.id IS 'Идентификатор';
COMMENT ON COLUMN product.code IS 'Код';
COMMENT ON COLUMN product.name IS 'Наименование';

CREATE TABLE IF NOT EXISTS customer (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id int8 NOT NULL
);
COMMENT ON COLUMN customer.id IS 'Идентификатор';
COMMENT ON COLUMN customer.person_id IS 'Персона FK:diag.person';

CREATE TABLE IF NOT EXISTS customer_order (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_id int8 NOT NULL,
	employee_id int8,
	order_items jsonb NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp
);
COMMENT ON COLUMN customer_order.id IS 'Идентификатор';
COMMENT ON COLUMN customer_order.customer_id IS 'Покупатель FK:diag.customer';
COMMENT ON COLUMN customer_order.employee_id IS 'Покупатель FK:diag.employee';
COMMENT ON COLUMN customer_order.order_items IS 'Товары FK:diag.product';
COMMENT ON COLUMN customer_order.created_at IS 'Дата создания';
COMMENT ON COLUMN customer_order.updated_at IS 'Дата редактирования';

CREATE TABLE IF NOT EXISTS person (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id int8,
	first_name text NOT NULL,
	last_name text NOT NULL,
	full_name TSVECTOR GENERATED ALWAYS AS (
		setweight(to_tsvector('russian', first_name), 'C') || ' ' || setweight(to_tsvector('russian', last_name), 'B')
    ) STORED
);
COMMENT ON COLUMN person.id IS 'Идентификатор';
COMMENT ON COLUMN person.user_id IS 'Учетная запись FK:diag.user_t';
COMMENT ON COLUMN person.first_name IS 'Имя';
COMMENT ON COLUMN person.last_name IS 'Фамилия';
COMMENT ON COLUMN person.full_name IS 'Полное имя';

CREATE TABLE IF NOT EXISTS address (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	gar uuid,
	no_gar varchar(250)
);
COMMENT ON COLUMN address.id IS 'Идентификатор';
COMMENT ON COLUMN address.gar IS 'Адрес';
COMMENT ON COLUMN address.no_gar IS 'Адрес (ручной ввод)';

CREATE TABLE IF NOT EXISTS person_address (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id int8 NOT NULL,
	address_id int8 NOT NULL
);
COMMENT ON COLUMN person_address.id IS 'Идентификатор';
COMMENT ON COLUMN person_address.person_id IS 'Персона FK:diag.person';
COMMENT ON COLUMN person_address.address_id IS 'Адрес FK:diag.address';

CREATE TABLE IF NOT EXISTS employee (
	id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id int8 NOT NULL
);
COMMENT ON COLUMN employee.id IS 'Идентификатор';
COMMENT ON COLUMN employee.person_id IS 'Персона FK:diag.person';